name       : pan
version    : 0.140
release    : 1
source     :
    - http://pan.rebelbase.com/download/releases/0.140/source/pan-0.140.tar.gz : 5cd704963d18d55e681bb1f3db70826c9436c9b7c3c69ca8227e0436bb35f928
license    : GPL-2.0
component  : office
summary    : A powerful and user-friendly Usenet newsreader for GTK+
description: |
    A powerful and user-friendly Usenet newsreader for GTK+
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(enchant)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(webkitgtk-3.0)
    - pkgconfig(zlib)
setup      : |
    %configure \
        --enable-gtr \
        --enable-libnotify \
        --with-dbus \
        --with-gmime-crypto \
        --with-gnutls \
        --with-gtkspell \
        --with-gtk3 \
        --with-webkit
build      : |
    %make
install    : |
    %make_install
