name       : pan
version    : '0.142'
release    : 3
source     :
    - http://pan.rebelbase.com/download/releases/0.142/source/pan-0.142.tar.bz2 : 12d776e981a32123a18f02424173910ab3bf5856ead416ea33b83d927ab42f93
license    : GPL-2.0
component  : office
summary    : A powerful and user-friendly Usenet newsreader for GTK+
description: |
    A powerful and user-friendly Usenet newsreader for GTK+
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(enchant)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(zlib)
    - itstool
setup      : |
    %configure \
        --enable-gtr \
        --enable-libnotify \
        --with-dbus \
        --with-gmime-crypto \
        --with-gnutls \
        --with-gtkspell \
        --with-gtk3
build      : |
    %make
install    : |
    %make_install
