name       : pan
version    : '0.146'
release    : 6
source     :
    - http://pan.rebelbase.com/download/releases/0.146/source/pan-0.146.tar.gz : 4f265268e47ff7cb144236e577fdcb82b7a1e81d411c6bc05d8387deac136d67
license    : GPL-2.0-or-later
component  : office
summary    : A powerful and user-friendly Usenet newsreader for GTK+
description: |
    A powerful and user-friendly Usenet newsreader for GTK+
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(enchant-2)
    - pkgconfig(enchant)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(zlib)
    - itstool
setup      : |
    autoreconf -vi
    %configure \
        --enable-gtr \
        --enable-libnotify \
        --with-dbus \
        --with-gmime-crypto \
        --with-gnutls \
        --with-gtkspell \
        --with-gtk3
build      : |
    %make
install    : |
    %make_install
