name       : pan
version    : '0.145'
release    : 4
source     :
    - https://github.com/GNOME/pan/archive/PAN_0_145.tar.gz : b43cd17811f2652bef16c91ffd476b491e7f4423e2ec4648ce62dd24fbe03ddb
license    : GPL-2.0
component  : office
summary    : A powerful and user-friendly Usenet newsreader for GTK+
description: |
    A powerful and user-friendly Usenet newsreader for GTK+
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(enchant)
    - pkgconfig(gmime-2.6)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(zlib)
    - itstool
setup      : |
    autoreconf -vi
    %configure \
        --enable-gtr \
        --enable-libnotify \
        --with-dbus \
        --with-gmime-crypto \
        --with-gnutls \
        --with-gtkspell \
        --with-gtk3
build      : |
    %make
install    : |
    %make_install
