name       : pan
version    : '0.149'
release    : 10
source     :
    - http://pan.rebelbase.com/download/releases/0.149/source/pan-0.149.tar.gz : 2445252125bc56d022dda1236adf80ae85274b41e5002c5667b0e032725b32b7
homepage   : http://pan.rebelbase.com/
license    : GPL-2.0-or-later
component  : office
summary    : A powerful and user-friendly Usenet newsreader for GTK+
description: |
    A powerful and user-friendly Usenet newsreader for GTK+
builddeps  :
    - pkgconfig(dbus-1)
    - pkgconfig(enchant-2)
    - pkgconfig(gmime-3.0)
    - pkgconfig(gnome-keyring-1)
    - pkgconfig(gnutls)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(zlib)
    - itstool
setup      : |
    %configure \
        --enable-gtr \
        --enable-libnotify \
        --with-dbus \
        --with-gmime-crypto \
        --with-gnutls \
        --with-gtkspell \
        --with-gtk3
build      : |
    %make
install    : |
    %make_install
